id: gitlab
name: Gitlab
description: The all-in-one DevOps platform for seamless collaboration and continuous delivery.
category: developer
website: https://docs.gitlab.com/ee/install/docker.html
services:
- name: gitlab
  image: gitlab/gitlab-ce:19.1.8-ce.0
  port: 80
  public: true
  mem_request_mb: 2048
  mem_limit_mb: 4096
  cpu_request_m: 500
  cpu_limit_m: 2000
  volumes:
  - name: gitlab-data
    mount_path: /var/opt/gitlab
    size_gb: 20
  - name: gitlab-config
    mount_path: /etc/gitlab
    size_gb: 5
  - name: gitlab-logs
    mount_path: /var/log/gitlab
    size_gb: 5
